# Generated by Django 5.1.4 on 2024-12-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_song_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_songs', models.ManyToManyField(blank=True, related_name='liked_by', to='music.song')),
            ],
        ),
    ]
